// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcwcwdteifgcpdpzmvkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxjd2N3ZHRlaWZnY3BkcHptdmt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MzUzNTIsImV4cCI6MjA3MzUxMTM1Mn0.eSah3yU2sNE6zcVbvzUyE3dkxUu7Jk8JJ2EJqQmORW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});